/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { UserCredentials } from "./components/login-component/login-component";
export namespace Components {
    interface CtButton {
        "disabled": boolean;
        "text": string;
    }
    interface CtLogin {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCtButtonElement extends Components.CtButton, HTMLStencilElement {
    }
    var HTMLCtButtonElement: {
        prototype: HTMLCtButtonElement;
        new (): HTMLCtButtonElement;
    };
    interface HTMLCtLoginElement extends Components.CtLogin, HTMLStencilElement {
    }
    var HTMLCtLoginElement: {
        prototype: HTMLCtLoginElement;
        new (): HTMLCtLoginElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ct-button": HTMLCtButtonElement;
        "ct-login": HTMLCtLoginElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CtButton {
        "disabled"?: boolean;
        "onBtnClick"?: (event: CustomEvent<any>) => void;
        "text": string;
    }
    interface CtLogin {
        "onLogin"?: (event: CustomEvent<UserCredentials>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ct-button": CtButton;
        "ct-login": CtLogin;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ct-button": LocalJSX.CtButton & JSXBase.HTMLAttributes<HTMLCtButtonElement>;
            "ct-login": LocalJSX.CtLogin & JSXBase.HTMLAttributes<HTMLCtLoginElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
